name: Build AudioSwitcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7.2'  # AudioSwitcher uses .NET Framework, not .NET Core

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: msbuild FortyOne.AudioSwitcher.sln /p:Configuration=Release
